/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BandsBandSlugRouteImport } from './routes/bands/$bandSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BandsBandSlugRoute = BandsBandSlugRouteImport.update({
  id: '/bands/$bandSlug',
  path: '/bands/$bandSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bands/$bandSlug': typeof BandsBandSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bands/$bandSlug': typeof BandsBandSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bands/$bandSlug': typeof BandsBandSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bands/$bandSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bands/$bandSlug'
  id: '__root__' | '/' | '/bands/$bandSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BandsBandSlugRoute: typeof BandsBandSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bands/$bandSlug': {
      id: '/bands/$bandSlug'
      path: '/bands/$bandSlug'
      fullPath: '/bands/$bandSlug'
      preLoaderRoute: typeof BandsBandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BandsBandSlugRoute: BandsBandSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
